#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to your Bravura Safe server
  https://safe.hitachi-id.net

Complete documentation:
  https://help.safe.hitachi-id.net/hosting/

Configuration:
  Configuration changes can be made in /root/bwdata/config.yml and
  /root/bwdata/env/global.override.env

Common commands:
  /root/bravura.sh stop
  /root/bravura.sh restart
  /root/bravura.sh rebuild

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
