#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

#
# Setup Bitwarden Installer
# ref: https://help.safe.hitachi-id.net/article/install-on-premise/
#

docker pull bravura_vault/setup

curl -s -o /root/bravura.sh \
    https://raw.githubusercontent.com/Hitachi-ID/bravura-safe_server/master/scripts/bravura.sh

chmod +x /root/bravura.sh
